output-format: pylint

strictness: veryhigh
test-warnings: true
doc-warnings: true
member-warnings: true

uses:
    - django
    - celery
    - flask

dodgy:
    run: true

frosted:
    run: true

mccabe:
    run: true

pep257:
    run: true
    disable:
        - D200 # One-line docstrings can not fit into more lines
        - D203 # 1 blank line required before class docstring
        - D204 # 1 blank line required after class docstring
        - D205 # 1 blank line required between summary line and description

pep8:
    run: true
    full: true 

profile-validator:
    run: true

pyflakes:
    run: true

pylint:
    run: true

pyroma:
    run: true

vulture:
    run: true
