output-format: pylint

ignore-paths:
    - unidown/modules/data/protobuf
    - unidown\modules\data\protobuf # for windows, see issue #203

strictness: veryhigh
test-warnings: true
doc-warnings: true
member-warnings: true

python-targets:
    - 3

uses:
    - django
    - celery
    - flask

dodgy:
    run: true

frosted:
    run: true

mccabe:
    run: true

pep257:
    run: true
    disable:
        - D105 # Missing docstring in magic method
        - D200 # One-line docstrings can not fit into more lines
        - D203 # 1 blank line required before class docstring
        - D204 # 1 blank line required after class docstring
        - D205 # 1 blank line required between summary line and description

pep8:
    run: false # pylint will check
    full: true
    options:
        max-line-length: 120

profile-validator:
    run: true

pyflakes:
    run: true

pylint:
    run: true

pyroma:
    run: true

vulture:
    run: true
