language: python
os: linux

jobs:
  include:
  - python: "3.7"
    env: PY_VERSION=py37
  - python: "3.8"
    env: PY_VERSION=py38
  - python: "3.9"
    env: PY_VERSION=py39
  allow_failures:
  - python: "3.9"

addons:
  apt:
    update: true

before_install:
  - sudo apt-get install jq
  - curl -LSs "$(curl -LSs https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | endswith(".jar"))) | .[0].browser_download_url')" -o codacy-coverage-reporter-assembly.jar

install:
  - pip install --upgrade -e .[dev]
  - cd test-plugin
  - pip install --upgrade -e .
  - cd ..
  - pip install codecov

script:
  - python setup.py clean --all
  - python setup.py bdist_wheel
  - pytest -v --cov-config=.coveragerc --cov=unidown --cov-report=xml
  - python setup.py check -v -m -s
  - twine check dist/*
  - unidown --version
  - sphinx-build -b html ./doc/source/ ./build/doc/html/
  - sphinx-build -b linkcheck ./doc/source/ ./build/doc/linkcheck/

after_success:
  - codecov
  - java -jar codacy-coverage-reporter-assembly.jar report -l Python -r coverage.xml

deploy:
  - provider: script
    script: twine upload -u $PYPI_USER -p $PYPI_PASSWORD --skip-existing dist/*
    on:
      branch: master
      repo: IceflowRE/unidown
      tags: true
